name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

env:
  SLUG: jetix-store-toolkit

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer

      - name: Install JS dependencies
        run: npm ci --ignore-scripts

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader --quiet

      - name: Build plugin
        run: npm run release-github

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          BUILD_DIR: build/jetix-store-toolkit
